import { Listing, Seller } from "./types";
import { generatePlaceholder } from "./placeholder-images";

export const sellers: Seller[] = [
  {
    id: "s1",
    companyName: "Pacific SMT Solutions",
    contactName: "James Chen",
    email: "james@pacificsmt.com",
    phone: "(408) 555-0142",
    location: "San Jose, CA",
    description: "Specializing in used and refurbished SMT and PCB fabrication equipment since 2005.",
  },
  {
    id: "s2",
    companyName: "MidWest PCB Equipment",
    contactName: "Sarah Miller",
    email: "sarah@midwestpcb.com",
    phone: "(312) 555-0198",
    location: "Chicago, IL",
    description: "Full-service PCB equipment dealer with on-site installation support.",
  },
  {
    id: "s3",
    companyName: "EuroTech Assembly",
    contactName: "Klaus Weber",
    email: "klaus@eurotechasm.com",
    phone: "+49 89 555 0234",
    location: "Munich, Germany",
    description: "European distributor of high-end assembly and fabrication equipment.",
  },
  {
    id: "s4",
    companyName: "Dragon Circuit Equipment",
    contactName: "Wei Lin",
    email: "wei@dragoncircuit.com",
    phone: "+886 2 555 0789",
    location: "Taipei, Taiwan",
    description: "Asia-Pacific dealer specializing in PCB drilling, plating, and imaging lines.",
  },
];

const SMT = "https://www.smtnet.com/media/images/";

function fabImg(equipment: string): string[] {
  return [generatePlaceholder(equipment, "PCB Fabrication")];
}
function crossImg(equipment: string): string[] {
  return [generatePlaceholder(equipment, "Cross-cutting")];
}

export const listings: Listing[] = [
  // ── PCB Fabrication ──
  {
    id: "1",
    title: "Copper Clad Laminate Cut-to-Size Line",
    equipment: "Panel Cutter",
    category: "Material & Panel Preparation",
    categoryGroup: "PCB Fabrication",
    brand: "Burkle",
    model: "CLC-1200",
    year: 2019,
    price: 95000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "Blade replaced 2024. Alignment calibrated.",
    pictures: fabImg("Panel Cutter"),
    sellerId: "s1",
    createdAt: "2024-12-01",
  },
  {
    id: "2",
    title: "Direct Imaging System LDI",
    equipment: "Laser Direct Imager",
    category: "Inner-Layer Imaging",
    categoryGroup: "PCB Fabrication",
    brand: "Orbotech",
    model: "Nuvogo 800",
    year: 2021,
    price: 520000,
    storageLocation: "Taipei, Taiwan",
    condition: "Like New",
    service: "Under manufacturer warranty. Less than 8000 hours.",
    pictures: fabImg("Laser Direct Imager"),
    sellerId: "s4",
    createdAt: "2024-11-15",
  },
  {
    id: "3",
    title: "Horizontal DES Line",
    equipment: "Develop-Etch-Strip System",
    category: "Develop / Etch / Strip (DES)",
    categoryGroup: "PCB Fabrication",
    brand: "Atotech",
    model: "UniPlate DES-H",
    year: 2018,
    price: 280000,
    storageLocation: "Munich, Germany",
    condition: "Refurbished",
    service: "Full chemical system overhaul. New rollers and spray bars.",
    pictures: fabImg("DES System"),
    sellerId: "s3",
    createdAt: "2024-10-20",
  },
  {
    id: "4",
    title: "AOI Inner-Layer Scanner",
    equipment: "AOI Scanner",
    category: "Inner-Layer Inspection",
    categoryGroup: "PCB Fabrication",
    brand: "Orbotech",
    model: "InspirON 4800",
    year: 2020,
    price: 340000,
    storageLocation: "Taipei, Taiwan",
    condition: "Used - Good",
    service: "Optics cleaned and recalibrated. Software current.",
    pictures: fabImg("AOI Scanner"),
    sellerId: "s4",
    createdAt: "2024-09-10",
  },
  {
    id: "5",
    title: "Oxide Treatment Line",
    equipment: "Black Oxide System",
    category: "Oxide & Bonding Treatment",
    categoryGroup: "PCB Fabrication",
    brand: "Atotech",
    model: "BondFilm Plus",
    year: 2017,
    price: 175000,
    storageLocation: "Chicago, IL",
    condition: "Used - Good",
    service: "Chemical tanks relined 2023. Heaters and pumps serviced.",
    pictures: fabImg("Oxide System"),
    sellerId: "s2",
    createdAt: "2024-11-01",
  },
  {
    id: "6",
    title: "Vacuum Lamination Press",
    equipment: "Lamination Press",
    category: "Lay-up & Lamination",
    categoryGroup: "PCB Fabrication",
    brand: "Burkle",
    model: "MTP-1600",
    year: 2019,
    price: 410000,
    storageLocation: "Munich, Germany",
    condition: "Refurbished",
    service: "New platens and hydraulic seals. Temperature uniformity verified.",
    pictures: fabImg("Lamination Press"),
    sellerId: "s3",
    createdAt: "2024-08-15",
  },
  {
    id: "7",
    title: "6-Spindle CNC Drilling Machine",
    equipment: "CNC Drill",
    category: "Drilling",
    categoryGroup: "PCB Fabrication",
    brand: "Schmoll",
    model: "MDI-6V",
    year: 2020,
    price: 385000,
    storageLocation: "Taipei, Taiwan",
    condition: "Like New",
    service: "Spindles rebuilt. Drill bit management system included.",
    pictures: fabImg("CNC Drill"),
    sellerId: "s4",
    createdAt: "2024-12-05",
  },
  {
    id: "8",
    title: "Desmear & Electroless Copper Line",
    equipment: "Desmear System",
    category: "Desmear & Hole Metallization",
    categoryGroup: "PCB Fabrication",
    brand: "Atotech",
    model: "Uniplate PTH",
    year: 2018,
    price: 220000,
    storageLocation: "Chicago, IL",
    condition: "Used - Good",
    service: "Full chemical analysis and tank reconditioning.",
    pictures: fabImg("Desmear System"),
    sellerId: "s2",
    createdAt: "2024-07-20",
  },
  {
    id: "9",
    title: "Vertical Continuous Plating Line",
    equipment: "Plating Line",
    category: "Electroplating",
    categoryGroup: "PCB Fabrication",
    brand: "Atotech",
    model: "UniPlate VCP-42",
    year: 2019,
    price: 650000,
    storageLocation: "Taipei, Taiwan",
    condition: "Used - Good",
    service: "Anode baskets replaced. Rectifiers tested. Throw specification met.",
    pictures: fabImg("Plating Line"),
    sellerId: "s4",
    createdAt: "2024-06-10",
  },
  {
    id: "10",
    title: "Solder Mask Spray Coater",
    equipment: "Coating Machine",
    category: "Solder Mask",
    categoryGroup: "PCB Fabrication",
    brand: "Other",
    model: "CSM-800 Curtain Coater",
    year: 2017,
    price: 125000,
    storageLocation: "San Jose, CA",
    condition: "Used - Fair",
    service: "Pump system replaced. Coating thickness within spec.",
    pictures: fabImg("Coating Machine"),
    sellerId: "s1",
    createdAt: "2024-05-01",
  },
  {
    id: "11",
    title: "HASL Lead-Free Surface Finish Line",
    equipment: "HASL Machine",
    category: "Surface Finish",
    categoryGroup: "PCB Fabrication",
    brand: "Other",
    model: "HAL-500LF",
    year: 2016,
    price: 89000,
    storageLocation: "Chicago, IL",
    condition: "Refurbished",
    service: "Solder pot rebuilt with lead-free alloy. Air knife replaced.",
    pictures: fabImg("HASL Machine"),
    sellerId: "s2",
    createdAt: "2024-11-20",
  },
  {
    id: "12",
    title: "CNC Router / Depaneling System",
    equipment: "CNC Router",
    category: "Profiling & Routing",
    categoryGroup: "PCB Fabrication",
    brand: "Pluritec",
    model: "MEGA-T6",
    year: 2021,
    price: 195000,
    storageLocation: "Munich, Germany",
    condition: "Like New",
    service: "Less than 2000 hours. All spindles and tooling included.",
    pictures: fabImg("CNC Router"),
    sellerId: "s3",
    createdAt: "2024-12-10",
  },
  {
    id: "13",
    title: "Flying Probe Bare Board Tester",
    equipment: "Flying Probe Tester",
    category: "Bare-Board Electrical Test",
    categoryGroup: "PCB Fabrication",
    brand: "ATG Luther & Maelzer",
    model: "A7a",
    year: 2020,
    price: 310000,
    storageLocation: "Taipei, Taiwan",
    condition: "Used - Good",
    service: "Probes replaced. Firmware updated. Accuracy verified.",
    pictures: fabImg("Flying Probe Tester"),
    sellerId: "s4",
    createdAt: "2024-12-12",
  },
  {
    id: "14",
    title: "Automated Optical Metrology System",
    equipment: "3D Measurement System",
    category: "Final Inspection & Metrology",
    categoryGroup: "PCB Fabrication",
    brand: "Koh Young",
    model: "Meister S",
    year: 2022,
    price: 185000,
    storageLocation: "San Jose, CA",
    condition: "Like New",
    service: "Demo unit with minimal usage. Full warranty transferable.",
    pictures: fabImg("3D Measurement"),
    sellerId: "s1",
    createdAt: "2024-10-05",
  },
  {
    id: "15",
    title: "Wastewater Treatment System",
    equipment: "Effluent Treatment Plant",
    category: "Chemistry, Water & Effluent",
    categoryGroup: "PCB Fabrication",
    brand: "Other",
    model: "EcoWater PCT-200",
    year: 2018,
    price: 145000,
    storageLocation: "Chicago, IL",
    condition: "Used - Good",
    service: "Membranes replaced 2024. Meets discharge compliance.",
    pictures: fabImg("Effluent Treatment"),
    sellerId: "s2",
    createdAt: "2024-12-15",
  },

  // ── PCB Assembly (PCBA) ──
  {
    id: "16",
    title: "Dry Cabinet Component Storage Tower",
    equipment: "Dry Cabinet",
    category: "Material Storage & Kitting",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Other",
    model: "MSD-1200F",
    year: 2022,
    price: 12000,
    storageLocation: "San Jose, CA",
    condition: "New",
    service: "New unit. Humidity monitoring and reel tracking included.",
    pictures: [
      `${SMT}md_Juki%20FES%20Cart%201%208mm%20MRE%20032025%20-%20Copy3.jpg`,
    ],
    sellerId: "s1",
    createdAt: "2024-09-25",
  },
  {
    id: "17",
    title: "High-Accuracy Stencil Printer",
    equipment: "Screen Printer",
    category: "Stencil Printing",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "DEK",
    model: "Horizon 03iX",
    year: 2020,
    price: 72000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Vision system calibrated. Print accuracy within spec.",
    pictures: [
      `${SMT}DEK%20Horizon%2003iX%20screen%20printers%20(2016).jpg`,
    ],
    sellerId: "s3",
    createdAt: "2024-11-30",
  },
  {
    id: "18",
    title: "Inline Stencil Printer",
    equipment: "Screen Printer",
    category: "Stencil Printing",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "MPM",
    model: "Momentum II HiE",
    year: 2021,
    price: 85000,
    storageLocation: "Chicago, IL",
    condition: "Like New",
    service: "Barely used demo unit. Full 2D inspection option included.",
    pictures: [
      `${SMT}sm_Photo%20Apr%2007%202026,%206%2015%2030%20AM.jpg`,
    ],
    sellerId: "s2",
    createdAt: "2024-08-01",
  },
  {
    id: "19",
    title: "High-Speed Chip Mounter",
    equipment: "Chip Mounter",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Fuji",
    model: "NXT III",
    year: 2019,
    price: 185000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "Full PM completed June 2024. All feeders serviced.",
    pictures: [
      `${SMT}md_nxt11.jpg`,
    ],
    sellerId: "s1",
    createdAt: "2024-12-01",
  },
  {
    id: "20",
    title: "SMT Placement System",
    equipment: "Placement Machine",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "ASM/Siemens",
    model: "SIPLACE X4S",
    year: 2021,
    price: 220000,
    storageLocation: "Chicago, IL",
    condition: "Like New",
    service: "Under manufacturer warranty. Less than 5000 hours.",
    pictures: [
      `${SMT}sm_CC.png`,
    ],
    sellerId: "s2",
    createdAt: "2024-11-15",
  },
  {
    id: "21",
    title: "Flexible Mounter",
    equipment: "Flexible Mounter",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Juki",
    model: "KE-3020VA",
    year: 2018,
    price: 145000,
    storageLocation: "Taipei, Taiwan",
    condition: "Refurbished",
    service: "Fully refurbished with new servo motors and vision upgrade.",
    pictures: [
      `${SMT}sm_Photo%20Apr%2007%202026,%206%2000%2024%20AM.jpg`,
    ],
    sellerId: "s4",
    createdAt: "2024-12-10",
  },
  {
    id: "22",
    title: "10-Zone Nitrogen Reflow Oven",
    equipment: "Reflow Oven",
    category: "Reflow Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Heller",
    model: "1809 MK5",
    year: 2023,
    price: 75000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "Complete PM with new heating elements. Profile verified.",
    pictures: [
      `${SMT}Photo%20Apr%2007%202026,%206%2018%2029%20AM.jpg`,
    ],
    sellerId: "s1",
    createdAt: "2024-10-20",
  },
  {
    id: "23",
    title: "13-Zone Reflow Oven",
    equipment: "Reflow Oven",
    category: "Reflow Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Heller",
    model: "2043 MK5",
    year: 2022,
    price: 95000,
    storageLocation: "Chicago, IL",
    condition: "New",
    service: "Brand new, never installed. Full manufacturer warranty.",
    pictures: [
      `${SMT}md_HELLER%202043%20MK5%20REFLOW%20OVEN.png`,
    ],
    sellerId: "s2",
    createdAt: "2024-12-12",
  },
  {
    id: "24",
    title: "8-Zone Reflow Oven",
    equipment: "Reflow Oven",
    category: "Reflow Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Vitronics Soltec",
    model: "XPM3-1030",
    year: 2018,
    price: 45000,
    storageLocation: "Munich, Germany",
    condition: "Used - Fair",
    service: "Functional with some zone variation. Sold as-is.",
    pictures: [
      `${SMT}md_Vitronics%20Soltec%207038.jpg`,
    ],
    sellerId: "s3",
    createdAt: "2024-04-15",
  },
  {
    id: "25",
    title: "Inline 3D AOI System",
    equipment: "3D AOI",
    category: "Inline Inspection",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Koh Young",
    model: "Zenith Alpha",
    year: 2023,
    price: 195000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Annual calibration completed. Software updated.",
    pictures: [
      `${SMT}Photo%20Apr%2007%202026,%206%2020%2024%20AM.jpg`,
    ],
    sellerId: "s3",
    createdAt: "2024-09-10",
  },
  {
    id: "26",
    title: "3D Solder Paste Inspection System",
    equipment: "SPI Machine",
    category: "Inline Inspection",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Other",
    model: "PARMI SigmaX Blue",
    year: 2018,
    price: 88000,
    storageLocation: "Taipei, Taiwan",
    condition: "Refurbished",
    service: "Factory refurbished with new optics and updated software.",
    pictures: [
      `${SMT}PARMI%20SigmaX%20Blue,%203D%20SPI%20(2016-2018).jpg`,
    ],
    sellerId: "s4",
    createdAt: "2024-10-05",
  },
  {
    id: "27",
    title: "Desktop AOI System",
    equipment: "AOI Machine",
    category: "Inline Inspection",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Mirtec",
    model: "MV-6 OMNI",
    year: 2022,
    price: 89000,
    storageLocation: "Chicago, IL",
    condition: "Like New",
    service: "Demo unit with minimal usage. Warranty transferable.",
    pictures: [
      `${SMT}md_PHOTO-2025-03-19-12-11-43%203.jpg`,
    ],
    sellerId: "s2",
    createdAt: "2024-12-08",
  },
  {
    id: "28",
    title: "Lead-Free Wave Solder Machine",
    equipment: "Wave Solder",
    category: "Wave Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Ersa",
    model: "POWERFLOW e N2",
    year: 2017,
    price: 62000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "New solder pot installed 2023. Nitrogen system functional.",
    pictures: [generatePlaceholder("Wave Solder", "PCB Assembly (PCBA)")],
    sellerId: "s1",
    createdAt: "2024-11-01",
  },
  {
    id: "29",
    title: "Selective Soldering Machine",
    equipment: "Selective Solder",
    category: "Selective Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Ersa",
    model: "ECOSELECT 4",
    year: 2019,
    price: 78000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Maintenance schedule followed. 4 solder pots included.",
    pictures: [generatePlaceholder("Selective Solder", "PCB Assembly (PCBA)")],
    sellerId: "s3",
    createdAt: "2024-07-20",
  },
  {
    id: "30",
    title: "High-Speed Chip Shooter",
    equipment: "Chip Shooter",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Juki",
    model: "KE-2080L",
    year: 2012,
    price: 38000,
    storageLocation: "San Jose, CA",
    condition: "Used - Fair",
    service: "Operational, shows cosmetic wear. Good for high-mix production.",
    pictures: [
      `${SMT}JUKI%20KE-2080L%20high-speed%20chip%20shooter%20(2009-2012)%20(2).jpg`,
    ],
    sellerId: "s1",
    createdAt: "2024-06-10",
  },
  {
    id: "31",
    title: "Inline Aqueous Cleaning System",
    equipment: "PCB Cleaner",
    category: "Cleaning",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Speedline",
    model: "Hydro-Clean 400",
    year: 2015,
    price: 28000,
    storageLocation: "Chicago, IL",
    condition: "Used - Fair",
    service: "Pumps and filters replaced. Functional but cosmetically worn.",
    pictures: [
      `${SMT}sm_EVO%20M-SBC%20stencil%20cleaner.jpg`,
    ],
    sellerId: "s2",
    createdAt: "2024-05-01",
  },
  {
    id: "32",
    title: "Selective Conformal Coating System",
    equipment: "Coating Machine",
    category: "Conformal Coating & Potting",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Nordson",
    model: "Select Coat SL-940",
    year: 2017,
    price: 55000,
    storageLocation: "Taipei, Taiwan",
    condition: "Used - Good",
    service: "Valve system overhauled. UV cure unit included.",
    pictures: [
      `${SMT}md_150.jpeg`,
    ],
    sellerId: "s4",
    createdAt: "2024-09-25",
  },
  {
    id: "33",
    title: "In-Circuit Test System",
    equipment: "ICT Tester",
    category: "Electrical Test",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Other",
    model: "Keysight i3070 Series 5",
    year: 2020,
    price: 135000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Fixture library available. Software license current.",
    pictures: [
      `${SMT}sm_LCR.jpg`,
    ],
    sellerId: "s3",
    createdAt: "2024-11-20",
  },
  {
    id: "34",
    title: "PCB Depaneling Router",
    equipment: "Depaneling Router",
    category: "Depaneling",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Nordson",
    model: "CR-5000",
    year: 2018,
    price: 42000,
    storageLocation: "Chicago, IL",
    condition: "Used - Fair",
    service: "Spindle rebuilt. Vision alignment operational. Cosmetic wear.",
    pictures: [generatePlaceholder("Depaneling Router", "PCB Assembly (PCBA)")],
    sellerId: "s2",
    createdAt: "2024-06-10",
  },
  {
    id: "35",
    title: "Modular Pick and Place",
    equipment: "Pick and Place",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Juki",
    model: "FX-3L",
    year: 2012,
    price: 55000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Recently serviced. Feeder carts included.",
    pictures: [
      `${SMT}JUKI%20FX-3L%20high-speed%20modular%20mounter%20(2010-2012)%20(2).jpg`,
    ],
    sellerId: "s3",
    createdAt: "2024-08-01",
  },
  {
    id: "36",
    title: "Compact Pick and Place",
    equipment: "Pick and Place",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Juki",
    model: "JM-100",
    year: 2024,
    price: 110000,
    storageLocation: "Taipei, Taiwan",
    condition: "Like New",
    service: "Less than 500 operating hours. All nozzles included.",
    pictures: [
      `${SMT}sm_Photo%20Apr%2007%202026,%206%2004%2003%20AM.jpg`,
    ],
    sellerId: "s4",
    createdAt: "2024-12-01",
  },
  {
    id: "37",
    title: "Laser Marking System",
    equipment: "Laser Marker",
    category: "Marking, Labeling & Traceability",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "LPKF",
    model: "InlineWeld 6200",
    year: 2021,
    price: 68000,
    storageLocation: "San Jose, CA",
    condition: "Like New",
    service: "Laser source has 90% life remaining. Vision alignment verified.",
    pictures: [generatePlaceholder("Laser Marker", "PCB Assembly (PCBA)")],
    sellerId: "s1",
    createdAt: "2024-12-01",
  },
  {
    id: "38",
    title: "Universal Placement Machine",
    equipment: "Placement Machine",
    category: "Component Placement",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Universal Instruments",
    model: "GC60",
    year: 2016,
    price: 65000,
    storageLocation: "Chicago, IL",
    condition: "Used - Good",
    service: "Servo motors replaced. All heads functional.",
    pictures: [
      `${SMT}md_IMG_8019.jpg`,
    ],
    sellerId: "s2",
    createdAt: "2024-07-15",
  },

  // ── Cross-cutting ──
  {
    id: "39",
    title: "Cleanroom HVAC & Air Handling Unit",
    equipment: "HVAC System",
    category: "Facility & Utilities",
    categoryGroup: "Cross-cutting",
    brand: "Other",
    model: "AHU-CLASS1000",
    year: 2019,
    price: 75000,
    storageLocation: "Taipei, Taiwan",
    condition: "Used - Good",
    service: "HEPA filters replaced. Temperature & humidity controls verified.",
    pictures: crossImg("HVAC System"),
    sellerId: "s4",
    createdAt: "2024-10-15",
  },
  {
    id: "40",
    title: "X-Ray Inspection System",
    equipment: "X-Ray Machine",
    category: "Metrology & Lab",
    categoryGroup: "Cross-cutting",
    brand: "Nordson",
    model: "XD7800NT",
    year: 2020,
    price: 290000,
    storageLocation: "Munich, Germany",
    condition: "Like New",
    service: "Tube replaced 2024. Full software license included.",
    pictures: [
      `${SMT}md_Front.png`,
    ],
    sellerId: "s3",
    createdAt: "2024-12-05",
  },
  {
    id: "41",
    title: "Microsection Lab Preparation System",
    equipment: "Microsection Equipment",
    category: "Metrology & Lab",
    categoryGroup: "Cross-cutting",
    brand: "Other",
    model: "Struers LaboPol-30",
    year: 2018,
    price: 22000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "Polishing heads replaced. Includes accessories and consumables.",
    pictures: crossImg("Microsection Equip."),
    sellerId: "s1",
    createdAt: "2024-07-01",
  },
  {
    id: "42",
    title: "ESD Workstation Package (10 stations)",
    equipment: "ESD Workstations",
    category: "ESD & Environmental",
    categoryGroup: "Cross-cutting",
    brand: "Other",
    model: "WS-ESD-10PK",
    year: 2023,
    price: 18000,
    storageLocation: "Chicago, IL",
    condition: "New",
    service: "New. Includes mats, wrist straps, grounding, and ionizers.",
    pictures: crossImg("ESD Workstations"),
    sellerId: "s2",
    createdAt: "2024-12-15",
  },
  {
    id: "43",
    title: "CAM Software Perpetual License + Workstation",
    equipment: "CAM System",
    category: "Software & CAD/CAM",
    categoryGroup: "Cross-cutting",
    brand: "Other",
    model: "Ucamco UcamX Premium",
    year: 2021,
    price: 35000,
    storageLocation: "Munich, Germany",
    condition: "Like New",
    service: "License transferable. Workstation with 64GB RAM included.",
    pictures: crossImg("CAM System"),
    sellerId: "s3",
    createdAt: "2024-11-05",
  },
  {
    id: "44",
    title: "Vacuum Reflow Oven",
    equipment: "Reflow Oven",
    category: "Reflow Soldering",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Other",
    model: "SMT Wertheim Vacuum M",
    year: 2021,
    price: 120000,
    storageLocation: "Munich, Germany",
    condition: "Used - Good",
    service: "Vacuum system serviced. Void-free soldering verified.",
    pictures: [
      `${SMT}sm_BB.png`,
    ],
    sellerId: "s3",
    createdAt: "2024-11-10",
  },
  {
    id: "45",
    title: "Conformal Coating Removal System",
    equipment: "Rework Station",
    category: "Conformal Coating & Potting",
    categoryGroup: "PCB Assembly (PCBA)",
    brand: "Other",
    model: "CCRco CCR2000",
    year: 2020,
    price: 32000,
    storageLocation: "San Jose, CA",
    condition: "Used - Good",
    service: "All tooling included. Extraction system functional.",
    pictures: [
      `${SMT}CCR2000.jpg`,
    ],
    sellerId: "s1",
    createdAt: "2024-08-20",
  },
];

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}

export function getSellerById(id: string): Seller | undefined {
  return sellers.find((s) => s.id === id);
}

export function getListingsBySeller(sellerId: string): Listing[] {
  return listings.filter((l) => l.sellerId === sellerId);
}
